# numpy

In [2]:
import numpy as np

dizi = np.array([0, 1, 2, 3])
dizi

array([0, 1, 2, 3])

In [22]:
yas_dizi = np.array([18, 25, 22, 34, 26, 27, 19, 28, 30, 24])
boy_dizi = np.array([1.81, 1.67, 1.71, 1.89, 1.79, 1.75, 1.80, 1.78, 1.89, 1.82])
agirlik_dizi = np.array([81, 72, 74, 88, 82, 77, 78, 70, 90, 85])

print(yas_dizi.shape)
print(boy_dizi.shape)
print(agirlik_dizi.shape)

(10,)
(10,)
(10,)


In [23]:
Listem = [False, 'Ali', 13, True]
Dizi = np.array(Listem)

print(Dizi)    # array elemanları tek tipe dönüştü

['False' 'Ali' '13' 'True']


In [29]:
yas_dizi[-3:] = np.array([99])
print(yas_dizi)

[18 25 22 34 26 27 19 99 99 99]


In [38]:
yas_dizi = np.append(yas_dizi, 200)
print(yas_dizi)

[ 18  25  22  34  26  27  19  99  99  99 100 101 102 100 101 102 200]


In [44]:
y = np.arange(8).reshape(2,4)
print(y)

[[0 1 2 3]
 [4 5 6 7]]


In [68]:
basketbol_takimi = np.array([[18, 25, 22, 34, 26, 27, 19, 28, 30, 24],
                             [1.81, 1.67, 1.71, 1.89, 1.79, 1.75, 1.80, 1.78, 1.89, 1.82],
                             [81, 72, 74, 88, 82, 77, 78, 70, 90, 85]])
print(basketbol_takimi)
print("Shape: ", basketbol_takimi.shape)    #.shape tuple yaratıyor. İçindeki elemanı alabiliyorsun yani.
print("( [1][3] ) 2'nin 4'ü: ", basketbol_takimi[1][3], "\n( [1,3] ) 2'nin 4'ü: ", basketbol_takimi[1,3])

[[18.   25.   22.   34.   26.   27.   19.   28.   30.   24.  ]
 [ 1.81  1.67  1.71  1.89  1.79  1.75  1.8   1.78  1.89  1.82]
 [81.   72.   74.   88.   82.   77.   78.   70.   90.   85.  ]]
Shape:  (3, 10)
( [1][3] ) 2'nin 4'ü:  1.89 
( [1,3] ) 2'nin 4'ü:  1.89


In [69]:
print(basketbol_takimi[0])
print(basketbol_takimi[0,])
print(basketbol_takimi[:,7])
print(basketbol_takimi[0:2,5:7])

[18. 25. 22. 34. 26. 27. 19. 28. 30. 24.]
[18. 25. 22. 34. 26. 27. 19. 28. 30. 24.]
[28.    1.78 70.  ]
[[27.   19.  ]
 [ 1.75  1.8 ]]


### Değişik dizi oluşturma yöntemleri:

In [70]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [75]:
np.ones([3,9])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [79]:
np.full([7,2],19)

array([[19, 19],
       [19, 19],
       [19, 19],
       [19, 19],
       [19, 19],
       [19, 19],
       [19, 19]])

In [89]:
np.linspace(4,12,5)    # 4 ve 12 dahil, eşit aralıklı 5 eleman

array([ 4.,  6.,  8., 10., 12.])

In [95]:
np.eye(4) # Identity Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Her bir eleman (element-wise) üzerinde çalışan fonksiyonlar:

In [104]:
print(y)    # y neydi, bir bakalım
print("\nShape of y: ", y.shape)

[[0 1 2 3]
 [4 5 6 7]]

Shape of y:  (2, 4)


In [105]:
print(np.square(y))    # her bir elemanın karesini alıyor.

[[ 0  1  4  9]
 [16 25 36 49]]


In [110]:
print(np.sqrt(y))    # her bir elemanın karekökünü alıyor.

[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]]


In [112]:
# trigonometrik işlemler ile her bir eleman üzerinde işlem yapıyoruz:
print(np.sin(y))
print(np.cos(y))
print(np.tan(y))

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]]
[[ 1.          0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029  0.75390225]]
[[ 0.          1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619  0.87144798]]


### Toplayıcı (Aggregator) fonksiyonlar:

In [136]:
print("yas max: ", np.max(yas_dizi))    # yas_dizi'ye append ile değişik rakamlar eklemiştik.
print("ağırlık max: ", np.max(agirlik_dizi))
print("boy max: ", np.max(boy_dizi))
print("\nyas min: ", np.min(yas_dizi))
print("ağırlık min: ", np.min(agirlik_dizi))
print("boy min: ", np.min(boy_dizi))
print("\nyas ort: ", np.mean(yas_dizi))
print("ağırlık ort: ", np.mean(agirlik_dizi))
print("boy ort: ", np.mean(boy_dizi))
print("\nyas standart sapma: ", np.std(yas_dizi))
print("ağırlık standart sapma: ", np.std(agirlik_dizi))
print("boy standart sapma: ", np.std(boy_dizi))

yas max:  200
ağırlık max:  90
boy max:  1.89

yas min:  18
ağırlık min:  70
boy min:  1.67

yas ort:  74.94117647058823
ağırlık ort:  79.7
boy ort:  1.791

yas standart sapma:  48.198694866678814
ağırlık standart sapma:  6.372597586541928
boy standart sapma:  0.06624952830020753
